### ISSUE TITLE
Android10 Crash!

### ISSUE THREAD

**Issue by zl910627** [robertlevonyan/MediaPicker#13]
```
Caused by: java.lang.IllegalStateException: BitmapFactory.decodeFile…context!!).path, options) must not be null
        at com.robertlevonyan.components.picker.PickerDialog.pickPhoto(PickerDialog.kt:529)
        at com.robertlevonyan.components.picker.PickerDialog.onActivityResult(PickerDialog.kt:485)
        at androidx.fragment.app.FragmentActivity.onActivityResult(FragmentActivity.java:170)
        at android.app.Activity.dispatchActivityResult(Activity.java:8110)
```

https://developer.android.com/about/versions/10/privacy/changes#scoped-storage

**Comment by robertlevonyan** [comment]
Fixed :)

**Comment by Dule95D** [comment]
Hello, thanks for this great library. Have you made commit after this fix because I'm still getting this error in latest version.
